#!/usr/bin/env python3
"""
Replace Steam Cloud URLs in the mod JSON with Cloudflare R2 URLs
using the mapping generated by generate_url_mapping.py.

Usage:
    python3 replace_urls.py \
        --mod-json ../original_mod.json \
        --mapping ../url_mapping.json \
        --output ../modified_mod.json
"""

import json
import argparse
import shutil
from pathlib import Path


def replace_urls_in_text(json_text: str, mapping: dict) -> tuple:
    """Replace all Steam URLs in JSON text with R2 URLs.
    Returns (modified_text, replacement_count, skipped_count)."""
    replaced = 0
    skipped = 0

    for steam_url, info in mapping.items():
        if info["status"] == "cached" and info["r2_url"]:
            count = json_text.count(steam_url)
            if count > 0:
                json_text = json_text.replace(steam_url, info["r2_url"])
                replaced += count
        else:
            count = json_text.count(steam_url)
            if count > 0:
                skipped += count

    return json_text, replaced, skipped


def main():
    parser = argparse.ArgumentParser(description='Replace Steam URLs with R2 URLs in mod JSON')
    parser.add_argument('--mod-json', required=True, help='Path to original mod JSON')
    parser.add_argument('--mapping', required=True, help='Path to url_mapping.json')
    parser.add_argument('--output', required=True, help='Path for modified JSON output')
    parser.add_argument('--tts-saves', default=None,
                        help='Also copy to TTS Saves directory (optional)')
    args = parser.parse_args()

    # Load mapping
    print(f"Loading URL mapping from {args.mapping}...")
    with open(args.mapping, 'r', encoding='utf-8') as f:
        mapping = json.load(f)

    cached = sum(1 for v in mapping.values() if v["status"] == "cached")
    missing = sum(1 for v in mapping.values() if v["status"] == "missing")
    print(f"  {cached} cached URLs (will be replaced)")
    print(f"  {missing} missing URLs (will be skipped)")

    # Check for placeholder URLs
    has_placeholder = any(
        v.get("r2_url", "").startswith("https://PLACEHOLDER")
        for v in mapping.values()
        if v["status"] == "cached"
    )
    if has_placeholder:
        print("\nERROR: url_mapping.json still contains PLACEHOLDER URLs!")
        print("Run generate_url_mapping.py with your actual --r2-base-url first.")
        return

    # Load and replace
    print(f"\nLoading mod JSON from {args.mod_json}...")
    with open(args.mod_json, 'r', encoding='utf-8') as f:
        json_text = f.read()

    print("Replacing URLs...")
    modified_text, replaced, skipped = replace_urls_in_text(json_text, mapping)

    print(f"  {replaced} URL occurrences replaced")
    print(f"  {skipped} URL occurrences skipped (missing assets)")

    # Verify the output is valid JSON
    print("Validating JSON...")
    json.loads(modified_text)  # Will raise if invalid
    print("  Valid JSON confirmed")

    # Check for remaining Steam URLs
    remaining = modified_text.count('cloud-3.steamusercontent.com')
    if remaining > 0:
        print(f"\n  WARNING: {remaining} Steam Cloud URL references still remain")
        print("  These are from missing/uncached assets")
    else:
        print("  No Steam Cloud URLs remaining - full migration!")

    # Write output
    with open(args.output, 'w', encoding='utf-8') as f:
        f.write(modified_text)
    print(f"\nModified JSON written to {args.output}")

    # Optionally copy to TTS Saves
    if args.tts_saves:
        save_path = Path(args.tts_saves) / "2139398986.json"
        shutil.copy2(args.output, save_path)
        print(f"Also copied to {save_path}")


if __name__ == '__main__':
    main()
